#ifndef SETTINGS_H
#define SETTINGS_H

const int TABLE_SIZE_PART1 = 1000;
const int C1_COEFF = 1;
const int MAX_LOAD_FACTOR = 7;

#define START_ALLOCATING_SIZE 100
#define START_AMOUNT_ALLOCATED_SEGMENTS 100

const int HASHING_BINARY_INT_RANDOM_CONST1 = 0x85EBCA6B;
const int HASHING_BINARY_INT_RANDOM_CONST2 = 0xC2B2AE35;

const int HASHING_POLYNOMIAL_RANDOM_CONST1 = 17;

const int MAX_ATTEMPTS_TO_INSERT_CUCKOO = 100;
const int MAX_ATTEMPTS_TO_REHASH_CUCKOO = 100;

const int PERFECT_HASHING_MAX_ATTEMPT_L1 = 100;
const int PERFECT_HASHING_MAX_ATTEMPT_L2 = 100;

#endif // SETTINGS_H
